### ISSUE TITLE
Typos in the app sliders

### ISSUE THREAD

**Issue by vascoamaralgrilo** [allfed/animal-feed-model#1]
"Pig Breeding" -> "Reduction Pig Breeding".
"Poultry Breeding" -> "Reduction Poultry Breeding".

**Comment by k-r-a-s-s** [comment]
I’ve moved platforms as heroku is removing their free tier in November.
Now using render.com
https://allfed-animal-feed.onrender.com/
It seems to be MUCH slower unfortunately, however I'm not going to spend time fixing it yet until consulting further on best practices on hosting.
I'll keep heroku live for now.

The app now looks to the github repo rather than hosting it’s own repo on heroku.com (so previously you had to push changes to github AND to heroku separately, now render.com treats github as the source)

This should happen automatically, if it is taking too long, there is an API call you can make to force redeploy from github. Will send on slack
